"""
AutoTrader Pro - Strategy Base Class
=====================================
Abstract base class that all trading strategies must inherit from.
Defines the common interface, configuration management, and the
StrategySignal data structure used to communicate signals.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, Dict, Any

import pandas as pd


@dataclass
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.

    Attributes:
        pair: Trading pair (e.g. 'BTC/INR').
        action: One of 'BUY', 'SELL', 'HOLD'.
        strategy: Name of the strategy that generated the signal.
        strength: Confidence / strength of the signal (0.0 to 1.0).
        reason: Human-readable explanation of why the signal was generated.
        metadata: Optional dict with extra data (stop loss, grid info, etc.).
    """

    pair: str
    action: str  # 'BUY', 'SELL', 'HOLD'
    strategy: str
    strength: float  # 0.0 to 1.0
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate signal fields after initialization."""
        if self.action not in ("BUY", "SELL", "HOLD"):
            raise ValueError(
                f"Invalid action '{self.action}'. Must be BUY, SELL, or HOLD."
            )
        self.strength = max(0.0, min(1.0, float(self.strength)))
        if self.metadata is None:
            self.metadata = {}


class StrategyBase(ABC):
    """
    Abstract base class for all trading strategies.

    Every strategy must:
      1. Inherit from this class.
      2. Call super().__init__() with a unique name and default parameters.
      3. Implement the analyze() method that processes candle data and
         returns an Optional[StrategySignal].

    Attributes:
        name: Unique identifier for the strategy.
        enabled: Whether the strategy is currently active.
        params: Dictionary of tunable strategy parameters.
    """

    def __init__(self, name: str, default_params: dict):
        """
        Initialize the strategy.

        Args:
            name: Unique name for this strategy instance.
            default_params: Default parameter dictionary. A copy is stored
                            so the original is never mutated.
        """
        self.name = name
        self.enabled = True
        self.params = default_params.copy()

    @abstractmethod
    def analyze(self, df: pd.DataFrame, pair: str) -> Optional[StrategySignal]:
        """
        Analyze candle data and return a signal or None.

        Args:
            df: OHLCV DataFrame with columns
                [timestamp, open, high, low, close, volume].
            pair: Trading pair identifier (e.g. 'BTC/INR').

        Returns:
            A StrategySignal if a trade opportunity is detected, else None.
        """
        pass

    def get_config(self) -> dict:
        """Return the current strategy configuration as a dictionary."""
        return {
            "name": self.name,
            "enabled": self.enabled,
            "params": self.params.copy(),
        }

    def update_params(self, new_params: dict):
        """
        Merge new parameter values into existing params.

        Args:
            new_params: Dictionary of parameter keys and their new values.
                        Only keys already present in self.params are updated;
                        unknown keys are also accepted (for extensibility).
        """
        self.params.update(new_params)

    def enable(self):
        """Enable the strategy so it participates in analysis cycles."""
        self.enabled = True

    def disable(self):
        """Disable the strategy so it is skipped during analysis cycles."""
        self.enabled = False

    def __repr__(self) -> str:
        status = "enabled" if self.enabled else "disabled"
        return f"<Strategy:{self.name} [{status}]>"
